### PR TITLE
Added only-on-change feature

### LINKED ISSUE #32: [Feature request] Don't appear until modify
Hi, thanks for the great package!

Although one set `org-appear-delay` to a large value to prevent showing the markers frequently when moving cursor, I personally prefer the [Typora](https://typora.io/) way: never show markers until one make changes inside the marker region by keyboard (Note that when clicking into the region, Typora also show the markers though). How do you think about this feature? Is it possible to achieve this in `org-appear`? Thanks!

### PR DESCRIPTION
**Pull request by SPFabGerman**
Closes #32.

I used a new local variable `org-appear--buffer-modified` and the `after-change-functions` hook to track if changes were made in the current buffer. This seems like the easiest method to me. I use a new local variable to avoid calling the functions twice (once for the `after-change-functions` hook and immediatly after for the `post-command-hook`)

I didn't encounter any problems and I would think this works as expected. Maybe @Yevgnen can give feedback if anything is missing or feels off?

### CODE REVIEW

**Comment by Yevgnen** [comment]
Hi, thanks for the quick response! I will try that and give a feedback!

**Comment by Yevgnen** [comment]
Seems so far so good for me!👍

**Comment by Yevgnen** [comment]
Found a small issue: when backward deleting a space right after a link, the raw format will be displayed after the deletion.

```
label *                                  # *=cursor, and a space before it
```
will trigger
```
[[http://...][label]*
```

Strictly speaking, I think the point is outside/right after the link😅. But after I check `Typora`, it does the same thing. So I think that's not really an issue and I just mark this up.

**Comment by awth13** [comment]
Thank you for your work, @SPFabGerman, and thanks for the excellent suggestion and testing, @Yevgnen!

This works really well with only a couple of minor issues. The issues, I think, do not block this PR but I will list them anyway.

1. In "normal" editing mode, i.e., non-evil, the invisible parts are sometimes not hidden when leaving the last element. Fixed in 9f212f56d532999da8c285d4de7c21b8bab51b52.
2. Toggling on mouse click respects the `org-appear-delay` setting but toggling on change does not. I think the two modes of operation should be entirely separated using a custom variable with `always`, `with-delay`, and `on-change` values. Implemented in #35 (without the `with-delay` option).
3. When the cursor moves through elements in the `on-change` mode (with `org-appear-only-on-change` set to `t`), the post command hook makes unnecessary calls to `org-appear--hide-invisible`. This also seems to cause the same movement issues we earlier encountered in #11. Fixed in https://github.com/awth13/org-appear/pull/35/commits/4b5cf5242427e597be1124f99bdf670485a3ba8a.

**Comment by awth13** [comment]
> Found a small issue: when backward deleting a space right after a link, the raw format will be displayed after the deletion.

This is due to the `org-element` API counting the whitespace after an element as part of the element. This proved to be necessary for `org-appear` -- when working with nested elements, `org-appear` needs at least one whitespace after the element to correctly distinguish children elements from parent elements.

**Comment by awth13** [comment]
With the issues listed above now fixed, I will prepare everything for a new release in #35. If you have any suggestions regarding the way I implemented the switching between `always` and `on-change` modes, please let me know!

**Pull request merged**
